### ISSUE TITLE
Can't see Back button in iOS 8 + iPhone 6

### ISSUE THREAD

**Issue by voznesenskym** [palmin/ios-multi-back-button#1] opened 2015-02-27 15:38 UTC
Forked, will try to fix...

**Comment by palmin** [comment] 2015-02-27 17:43
I do not have a iPhone 6, but just tried the example project with a iPhone 6 simulator and the back button looked just fine. 

Are you trying with the same project or a different one?

It is very easy to forget to include the image asset for ''<''.

**Comment by palmin** [comment] 2015-02-27 18:15
![iphone-6](https://cloud.githubusercontent.com/assets/1230554/6418377/ee160466-beb4-11e4-8db7-a74c23137703.png)

**Comment by palmin** [comment] 2015-02-28 09:06
The fix to https://github.com/palmin/ios-multi-back-button/issues/3 changed the way the back-button is drawn such that you do not need any image assets. 

Since I have not been able to reproduce this issue I will close it, but feel free to reopen with additional info if you are still having problems.

**Closed by palmin** 2015-02-28 09:06 UTC
